AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket for hosting static frontend site

Parameters:
  
  MyBucketName:
    Type: String
    Description: Name of the S3 bucket for static hosting


Resources:

  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MyBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  PublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${StaticSiteBucket.Arn}/*"


Outputs:

  BucketRegionalDomainName:
    Value: !GetAtt StaticSiteBucket.RegionalDomainName
